//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public string MaNV { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string QueQuan { get; set; }
        public string GioiTinh { get; set; }
        public string DanToc { get; set; }
        public string SoDienThoai { get; set; }
        public string MaPB { get; set; }
        public string MaCV { get; set; }
        public string MaHD { get; set; }
        public string MaTDHV { get; set; }
        public Nullable<int> BacLuong { get; set; }
    
        public virtual CHUCVU CHUCVU { get; set; }
        public virtual HOPDONGLAODONG HOPDONGLAODONG { get; set; }
        public virtual LUONG LUONG { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual PHONGBAN PHONGBAN { get; set; }
        public virtual TRINHDOHOCVAN TRINHDOHOCVAN { get; set; }
    }
}
