//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUYENDUNG
    {
        public string Email { get; set; }
        public string HoTen { get; set; }
        public string SDT { get; set; }
        public string KyNang { get; set; }
        public string GioiTinh { get; set; }
    }
}
